config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  
  devise_for :users
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :home, only:[:index ]
  resources :areas
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/area.rb
class Area < ApplicationRecord
end

app/models/programa.rb
class Programa < ApplicationRecord
  belongs_to :Area
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  def index
    @areas = Area.all
    render json: @areas, status: 200
  end

  def show
    @area = Area.find(params[:codigo_area])
  end
 
 
  def new 
  @area = Area.new
  render json: @area, status: 200
  end
  
  
  def create
    @area = Area.create!(
    codigo_area: params[:codigo_area],
    nombre_area: params[:nombre_area])
    if @area.save 
      redirect_to areas_path
    else 
      render :new 
    end 
    
  end
  def update 
    @area =  Area.find(params[:codigo_area])
    Area.update(
    codigo_area: params[:codigo_area],
    nombre_area: params[:nombre_area]
    )
    render json: @area, status: 200
   end 
  
  def destroy 
    @area =  Area.find(params[:codigo_area])
    Area.destroy!
    render status: 200

   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def show
  
  end

  def edit
    
  end
  
  def new
    
  end
  
 
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/areas/_area.html.erb
<tr>
    <td> <%= area.codigo_area %> </td>
    <td> <%= area.nombre_area %> </td>
</tr>

app/views/areas/index.html.erb
<head>
  <%= stylesheet_link_tag "areas" %>
</head>

<body>
 
    <nav id="nav-area">
        <section id="Index-Logo-area"><%= image_tag("logo.png", width: "80", height: "60")%></section>
        <section id="Index-Salir-area">
        <div id="Texto-Salir-area">
                <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete %>
            </div>
            
        </section>
    </nav>

    <main id="main-area" >
        <section class="Container-Lista-area">
            <div id="Titulo-Menu-area">
                <h2>Titulo</h2>
            </div>
            <div id="Menu">
                <ul class="area-Listas">
                    
                    <li class="Lista1-area"> <%= link_to "Nueva Area",  new_area_path, method: :get %></li>
                    <li class="Lista1-area"> <%= link_to "Editar Area", edit_area_path, method: :get %></a></li>
                </ul>
                <div id="volver-area">
                <%= link_to "volver", home_index_path, method: :get %>
                 </div>
                </div>
            
        </section>

        <section id="Index-Bienvenida-area">
            <table border=1, id="table-area"> 
                <tr>
                    <th>Codigo</th>
                    <th>nombre</th>
                </tr>

               <%= render @areas %>
                
            </table>
        </section>
        
    </main>

  
</body>
</html> 

app/views/areas/new.html.erb
<form  method="post">
  <label for="fname">Codigo De Area :</label><br>
  <input type="text" placeholder="Codigo De Area "><br>
  <label for="lname">Nombre De Area :</label><br>
  <input type="text" placeholder="Nombre de Area"<br><br>
  <input type="submit" value="crear">
</form>

app/views/home/index.html.erb
<head>
  <%= stylesheet_link_tag "home" %>
</head>

<body>
 
    <nav>
        <section id="Index-Logo-home"><%= image_tag("logo.png", width: "80", height: "60")%></section>
        <section id="Index-Salir-home">
            <div id="Texto-Salir-home">
                <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete %>
            </div>
        </section>
    </nav>

    <main>
        <section class="Container-Lista-home">
            <div id="Titulo-Menu-home">
                <h2>Titulo</h2>
            </div>
            <div id="Menu">
                <ul class="Home-Listas">
                    <li class="Lista1-home"><%= link_to "Areas", areas_path, method: :get %></li>
                    <li class="Lista1-home"><a href="#">Programacion</a></li>
                    <li class="Lista1-home"><a href="#">Descripcion</a></li>
                </ul>
            </div>
            
        </section>

        <section id="Index-Bienvenida-home">
            <h3>Bienvenidos</h3>
        </section>
        
    </main>

  
</body>
</html> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apk001</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <footer>
        <div id="info-footer">Version 1.0.0</div>
    </footer>
  </body>
</html>